---
  chunk:
    # [TODO] https://github.com/Mitanshk01/GFS-Distributed-Systems/issues/1
    # Chunk size in bytes (1 MB = 1048576 bytes)
    size: 1048576
    
    naming_pattern: "chunk_{id}"

    # Chunk verification
    checksum_algorithm: "sha256"
    verify_on_read: true

  chunk_server:
    max_chunks: 1000
  
    # Directory to store chunk data
    # Ensure this directory has sufficient permissions and storage
    storage_path: "../../storage/chunks"

  deletion:
    g_c_interval: 180
    retention_period: 300
    g_c_delete_batch_size: 100
    trash_dir_prefix: "/.trash/"

  # Health check configuration
  health:
    # Interval between health checks(heart-beat) in seconds
    check_interval: 20
    
    # Timeout for health check responses in seconds
    timeout: 30
    
    # Maximum consecutive failures before marking chunk-server as down
    max_failures: 2

  metadata:
    database:
      type: "json"  # or "mysql", "postgresql"
      path: "../../storage/master/metadata.json"
      backup_interval: 30
    
    # Namespace settings
    max_filename_length: 255
    max_directory_depth: 64

  # Lease settings
  lease:
    # Duration of leases in seconds
    lease_timeout: 60

  operation_log:
    path: "../../storage/master/operation-log.json"

  replication:
    # Number of replicas for each chunk
    factor: 3
    
    # Timeout for replication operations in seconds
    timeout: 180

  server:
    host: "localhost"
    port: 5000
    max_connections: 100
    connection_timeout: 30
    # Maximum request size in bytes (default: 100MB)
    max_request_size: 104857600
    # Server thread pool size
    thread_pool_size: 50
