---
  server:
    host: "localhost"
    port: 5000
    max_connections: 100

  chunk:
    # [TODO] https://github.com/Mitanshk01/GFS-Distributed-Systems/issues/1
    # Chunk size in bytes (1 MB = 1048576 bytes)
    size: 1048576
    # Maximum number of chunks per server
    max_chunks: 1000
    # Directory to store chunk data
    storage_path: "/var/lib/mini-gfs/chunks"
    naming_pattern: "chunk_{id}"

  replication:
    factor: 3
    timeout: 30
    # Minimum number of successful replicas required
    min_success: 2

  health:
    # In seconds
    check_interval: 10
    timeout: 5
    # Maximum consecutive failures before marking chunk-server as down
    max_failures: 3
